###
POST http://localhost:8000/order HTTP/1.1
Content-Type: application/json

{
    "id": "110c9783-8ca1-467c-a4f4-5ee66fa4a5eb",
    "price": 12.99,
    "tax": 0.99
}

###
GET http://localhost:8000/order HTTP/1.1
Content-Type: application/json